name: Deploy UI5 Bot

on:
  push:
    branches:
      - main
    paths:
      - 'packages/blueskybotui5version/index.js'  # Only run when index.js changes
  workflow_dispatch:  # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH and Deploy
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit immediately if a command exits with a non-zero status

            echo "Navigating to bot directory..."
            cd /root/bluesky-bots/packages/blueskybotui5version

            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm install

            echo "Restarting the bot..."
            pm2 reload bluesky-ui5version-bot || pm2 start index.js --name bluesky-ui5version-bot

            echo "Deployment complete!"
